### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#20]

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/b138154fa00db89bae400aef77c18973081b0f768493653cdb4e51d733563a1f

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/f7b8dedee6fea3e053c3a733b8416186e81d425fea86a81e94ab09d47ad456bd

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square)![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square) <br /><br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br /><br /> ![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square) <br /><br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br /> ![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square) <br /><br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![PS and Via warning](https://img.shields.io/badge/Via%20and%20ProtocolSupport%20only%20work%20together%20on%20Paper%20servers%20or%20one%20of%20its%20forks-orange?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br /> ![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br /> ![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.1-SNAPSHOT (git-d3ff6f8e-b54)](https://img.shields.io/badge/Platform-velocity--3.0.1--SNAPSHOT (git--d3ff6f8e--b54)-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.1-SNAPSHOT (git-d3ff6f8e-b54)](https://img.shields.io/badge/Platform-velocity--3.0.1--SNAPSHOT (git--d3ff6f8e--b54)-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.1-SNAPSHOT (git-d3ff6f8e-b54)](https://img.shields.io/badge/Platform-velocity--3.0.1--SNAPSHOT%20%28git--d3ff6f8e--b54%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-PaperSpigot-"4c7641d" (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-22%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Spigot-596221b-9a1fc1e (MC: 1.12)](https://img.shields.io/badge/Platform-git--Spigot--596221b--9a1fc1e%20%28MC%3A%201.12%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Spigot-596221b-9a1fc1e (MC: 1.12)](https://img.shields.io/badge/Platform-git--Spigot--596221b--9a1fc1e%20%28MC%3A%201.12%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-PaperSpigot-"4c7641d" (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-22%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Purpur-1132 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Purpur--1132%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)
