### ISSUE TITLE
4.0.2-1.18-experimental1-SNAPSHOT :thonk:

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#21]
https://dump.viaversion.com/0a20cf37c1813058f2a9bf90a62325d786051b157e1c9febac94f93d4b4060d2

**Comment by Barvalg** [comment]
![Platform: 0.4.3+null-experimental18](https://img.shields.io/badge/Platform-0.4.3+null--experimental18-3498db?style=flat-square) <br />![ViaVersion (4.0.2-1.18-experimental1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-1.18-experimental1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/73d3b27269ea3bd4c6597105cbb3c15cc30bb5302c243bcc726de0b7c0ca72c6

**Comment by Barvalg** [comment]
![Platform: git-Airplane-"9f3cad3" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Airplane--%229f3cad3%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)
