### ISSUE TITLE
??

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#22]
### /viaversion dump Output

https://dump.viaversion.com/8366ff9d222114ee47dc9aa2b9243f4598a989f3b96901a54d431bb79ef137b1

### Console Error

https://paste.gg/p/anonymous/519fc9e77a184bd2ab93a3f45e23ff6b/files/2e65c4d6a5084751a105493bb819ccd6/raw

### Bug Description

Another plugin can not be enabled on server start when viaversion is installed.

### Steps to Reproduce

1.) Install both, tuske (https://github.com/Tuke-Nuke/TuSKe) and viaversion
2.) Start server

**Comment by Jo0001** [comment]
https://dump.viaversion.com/8366ff9d222114ee47dc9aa2b9243f4598a989f3b96901a54d431bb79ef137b1

**Comment by Jo0001** [comment]
https://dump.viaversion.com/1aee788f6d9c8900a3b95c837dd07810b0527426a5a78faba4473492c422053c

**Comment by Barvalg** [comment]
![Platform: 3.0.0](https://img.shields.io/badge/Platform-3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-xf0e91a4x (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f0e91a4%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"f0e91a4" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f0e91a4%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"f0e91a4" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f0e91a4%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/8366ff9d222114ee47dc9aa2b9243f4598a989f3b96901a54d431bb79ef137b1

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"f0e91a4" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f0e91a4%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"f0e91a4" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f0e91a4%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 0.4.3+null-experimental18](https://img.shields.io/badge/Platform-0.4.3+null--experimental18-3498db?style=flat-square) <br />![ViaVersion (4.0.2-1.18-experimental1-SNAPSHOT): Even with experimental-1.18-snapshot](https://img.shields.io/badge/ViaVersion%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20experimental-1.18-snapshot-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-1.18-experimental1-SNAPSHOT): Even with experimental-1.18-snapshot](https://img.shields.io/badge/ViaBackwards%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20experimental-1.18-snapshot-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-783 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--783%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-783 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--783%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-783 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--783%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: 0.4.3+null-experimental18](https://img.shields.io/badge/Platform-0.4.3+null--experimental18-3498db?style=flat-square) <br />![ViaVersion (4.0.2-1.18-experimental1-SNAPSHOT): Even with experimental-1.18-snapshot](https://img.shields.io/badge/ViaVersion%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20experimental--1.18--snapshot-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-1.18-experimental1-SNAPSHOT): Even with experimental-1.18-snapshot](https://img.shields.io/badge/ViaBackwards%20(4.0.2--1.18--experimental1--SNAPSHOT)-Even%20with%20experimental--1.18--snapshot-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.0](https://img.shields.io/badge/Platform-velocity--3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.0](https://img.shields.io/badge/Platform-velocity--3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/8057da2f9aac4d4458f39a2999f59f558042e50e11b3e31830899e5196729dea

**Comment by Barvalg** [comment]
![Platform: git-Paper-391 (MC: 1.16.4)](https://img.shields.io/badge/Platform-git--Paper--391 (MC: 1.16.4)-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)

**Comment by Barvalg** [comment]
![Platform: git-Paper-391 (MC: 1.16.4)](https://img.shields.io/badge/Platform-git--Paper--391%20%28MC%3A%201.16.4%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)

**Comment by Jo0001** [comment]
test
