### ISSUE TITLE
No dump

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#23]
no dump :rip:

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/892d7bfdd96734a556614f086b6ecc37e63f33e07d57e3f

**Comment by Jo0001** [comment]
https://dump.viaversion.com/21f4881f6ae8757689e1193d3a8136410f3425d7e1cef8f2f8d78c31196a88ad

**Comment by Barvalg** [comment]
![Platform: 0.4.14+v0.4.14--14--g2c22eab.dirty](https://img.shields.io/badge/Platform-0.4.14+v0.4.14--14--g2c22eab.dirty-3498db?style=flat-square) </br>![ViaVersion (4.1.0-1.18-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--1.18--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0-21w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--21w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/09b79cc22b226fe477a040486cd8e4de3f95a01c44b0a08b39cbac70c65cca9f

**Comment by Barvalg** [comment]
![Platform: git--Paper--790%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--790%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/21f4881f6ae8757689e1193d3a8136410f3425d7e1cef8f2f8d78c31196a88ad

**Comment by Jo0001** [comment]
https://dump.viaversion.com/34a9c9fbf4be735abb8409a64a50e51db26ab4c20368247ad5a49aa26a395e0c

**Comment by Jo0001** [comment]
https://dump.viaversion.com/34a9c9fbf4be735abb8409a64a50e51db26ab4c20368247ad5a49aa26a395e0c

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>
