### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#24]
xx

**Comment by Jo0001** [comment]
https://dump.viaversion.com/86ac3c03cb7bfac831c0222a7423982ee53133c021355f85bdfb12caf5132839

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae1ad9a5%3A497](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae1ad9a5%3A497-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/3412eaa08583b71b614c33a9daec142da29e31bf9659d94bbb76f25d3fffc781

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/2855c5b122899e81432830d7d198ba4c6511430a7ec4f22835828acaee59c831

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2----1.19.1----rc1----SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): 19 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-19%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/3412eaa08583b71b614c33a9daec142da29e31bf9659d94bbb76f25d3fffc781

**Comment by Jo0001** [comment]
https://dump.viaversion.com/3412eaa08583b71b614c33a9daec142da29e31bf9659d94bbb76f25d3fffc781

**Comment by Jo0001** [comment]
https://dump.viaversion.com/3412eaa08583b71b614c33a9daec142da29e31bf9659d94bbb76f25d3fffc781

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
