### ISSUE TITLE
reupload

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#40]
### '/viaversion dump' Output

https://pastebin.com/hHCsVpeb

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

<e>

### Steps to Reproduce

<e>

### Expected Behavior

<e>

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/342d0ba8715750c6c566c2dc2fe1c662898150dd738a1805534af299fb59d560

**Comment by Barvalg** [comment]
![Platform: 0.4.14+74--main](https://img.shields.io/badge/Platform-0.4.14+74--main-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<br>Put the jars into the mod folder.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>
