### ISSUE TITLE
test log

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#41]
### '/viaversion dump' Output

https://dump.viaversion.com/696b54aaa2861be739dbc78ae499ae01edaca3b783e240d88de0727c2d21687e

### Console Error

```
[Put the paste.gg link or text here.](https://pastebin.com/5BuYEuKW)
```

### Bug Description

https://pastebin.com/5BuYEuKW

### Steps to Reproduce

test

### Expected Behavior

test

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>invalid_entity,invalid_entity</details>

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>invalid_entity,invalid_entity</details>

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>invalid_entity,invalid_entity</details>
